Market Basket Analysis What is it? Market Basket Analysis is a modelling technique based upon the theory that if you buy a certain group of items, you are more (or less) likely to buy another group of items. For example, if you are in an English pub and you buy a pint of beer and don't buy a bar meal, you are more likely to buy crisps (US. chips…

In [156]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [157]:
#!pip install apyori

In [158]:
from apyori import apriori


In [176]:
store_data = pd.read_csv("AirQualityUCI.csv", header=None)
display(store_data.head())
print(store_data.shape)

0         1       2            3         4         5   \
0       Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)   
1  10/3/2004  18.00.00     2.6         1360       150      11.9   
2  10/3/2004  19.00.00       2         1292       112       9.4   
3  10/3/2004  20.00.00     2.2         1402        88         9   
4  10/3/2004  21.00.00     2.2         1376        80       9.2   

              6        7             8        9             10           11  \
0  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)   
1           1046      166          1056      113          1692         1268   
2            955      103          1174       92          1559          972   
3            939      131          1140      114          1555         1074   
4            948      172          1092      122          1584         1203   

     12    13      14  
0     T    RH      AH  
1  13.6  48.9  0.7578  
2  13.3  47.7  0.7255  
3  11.9    54  0.7502  
4    11    60  0.7867

(9358, 15)


In [177]:
#store_data.fillna(store_data.mean(numeric_only=True).round(1), inplace=True)


In [178]:
#store_data=store_data.replace(np.nan,0)


In [179]:
# Get Total Count of all Columns
count = store_data.replace(np.nan,0).isnull().sum().sum()
print('Number of NaN values present:' +str(count))

Number of NaN values present:0


In [180]:
store_data.shape

(9358, 15)

In [181]:
records = []
for i in range(1, store_data.shape[0]):
    records.append([str(store_data.values[i, j]) for j in range(0, store_data.shape[1])])

In [182]:
np_record=np.array(records)


In [183]:
import numpy as np
from sklearn.cluster import MeanShift, estimate_bandwidth

In [184]:
np_record.shape

(9357, 15)

## Turn Each Column to Clustered_Data
with Mean Shift

Output Shows Range of each Cluster as well

In [186]:

clustered_Data =[] 
labels=[]
cluster_centers=[]
labels_unique=[]
n_clusters_=[]
ranges_column=[]

for i in range(2,np_record.shape[1]):
    X=np_record[:,i].reshape(np_record[:,i].shape[0],1)

    X=X.astype('float64')
    if np.isnan(X).any() == True:
        print("There is NAN")
        X = np.nan_to_num(X)

    ms = MeanShift(bandwidth=None, bin_seeding=True)
    ms.fit(X)

    labels.append(ms.labels_)

    cluster_centers.append(ms.cluster_centers_)

    

    labels_unique.append(np.unique(ms.labels_))

    n_clusters_.append(len(np.unique(ms.labels_)))

 

    print("number of estimated clusters : %d" % len(np.unique(ms.labels_)))

    print(ms.labels_)
    clustered_Data.append(ms.labels_)

    arr=[]
    for k in np.unique(ms.labels_):
        print([min(X[ms.labels_==k]),max(X[ms.labels_==k])])
        arr.append([min(X[ms.labels_==k]),max(X[ms.labels_==k])])
    ranges_column.append(arr)

number of estimated clusters : 3
[0 0 0 ... 0 0 0]
[array([0.1]), array([11.9])]
[array([-200.]), array([-200.])]
[array([1428.]), array([1428.])]
number of estimated clusters : 2
[0 0 0 ... 0 0 0]
[array([647.]), array([2040.])]
[array([-200.]), array([-200.])]
number of estimated clusters : 14
[2 1 1 ... 0 0 0]
[array([-200.]), array([-200.])]
[array([7.]), array([128.])]
[array([129.]), array([305.])]
[array([434.]), array([488.])]
[array([306.]), array([426.])]
[array([501.]), array([565.])]
[array([639.]), array([737.])]
[array([575.]), array([635.])]
[array([743.]), array([840.])]
[array([872.]), array([899.])]
[array([1042.]), array([1084.])]
[array([926.]), array([974.])]
[array([1189.]), array([1189.])]
[array([1129.]), array([1129.])]
number of estimated clusters : 3
[0 0 0 ... 0 0 0]
[array([0.1]), array([63.7])]
[array([-200.]), array([-200.])]
[array([1321.]), array([1321.])]
number of estimated clusters : 3
[0 0 0 ... 0 0 0]
[array([383.]), array([1520.])]
[array([-200.])

# Original Data

In [187]:
np_record

array([['10/3/2004', '18.00.00', '2.6', ..., '13.6', '48.9', '0.7578'],
       ['10/3/2004', '19.00.00', '2', ..., '13.3', '47.7', '0.7255'],
       ['10/3/2004', '20.00.00', '2.2', ..., '11.9', '54', '0.7502'],
       ...,
       ['4/4/2005', '12.00.00', '2.4', ..., '26.9', '18.3', '0.6406'],
       ['4/4/2005', '13.00.00', '2.1', ..., '28.3', '13.5', '0.5139'],
       ['4/4/2005', '14.00.00', '2.2', ..., '28.5', '13.1', '0.5028']],
      dtype='<U13')

In [188]:
len(np_record)

9357

In [78]:
sum(labels==1)


1682

In [70]:
np_record.shape,np_record[0:10]

((9357, 15),
 array([['10/3/2004', '18.00.00', '0', '1360', '150', '11.9', '1046',
         '166', '1056', '113', '1692', '1268', '13.6', '48.9', '0.7578'],
        ['10/3/2004', '19.00.00', '0', '1292', '112', '9.4', '955', '103',
         '1174', '92', '1559', '972', '13.3', '47.7', '0.7255'],
        ['10/3/2004', '20.00.00', '0', '1402', '88', '9', '939', '131',
         '1140', '114', '1555', '1074', '11.9', '54', '0.7502'],
        ['10/3/2004', '21.00.00', '0', '1376', '80', '9.2', '948', '172',
         '1092', '122', '1584', '1203', '11', '60', '0.7867'],
        ['10/3/2004', '22.00.00', '0', '1272', '51', '6.5', '836', '131',
         '1205', '116', '1490', '1110', '11.2', '59.6', '0.7888'],
        ['10/3/2004', '23.00.00', '0', '1197', '38', '4.7', '750', '89',
         '1337', '96', '1393', '949', '11.2', '59.2', '0.7848'],
        ['11/3/2004', '00.00.00', '0', '1185', '31', '3.6', '690', '62',
         '1462', '77', '1333', '733', '11.3', '56.8', '0.7603'],
        ['11

(9358, 15)

## Reshape Data

In [213]:
clustered_Data=np.array(clustered_Data).transpose()

In [218]:
clustered_Data.shape

(9357, 13)

In [214]:
list(np.array(clustered_Data).T)

[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([2, 1, 1, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [215]:
type(records)

list

In [216]:
print(type(records))


<class 'list'>


## Numpy to List

cls_data variable contains clustered data

In [227]:
cls_data=[]
for i in range(clustered_Data.shape[0]):
    cls_data.append(list(clustered_Data[0]))

In [228]:
cls_data

[[0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,

In [234]:

association_rules = apriori(cls_data, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=1)
association_results = list(association_rules)

In [235]:
print("There are {} Relation derived.".format(len(association_results)))


There are 0 Relation derived.


In [236]:
for i in range(0, len(association_results)):
    print(association_results[i][0])

In [237]:
for item in association_results:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    # second index of the inner list
    print("Support: " + str(item[1]))

    # third index of the list located at 0th
    # of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

In [238]:
df.colums

NameError: name 'df' is not defined